apiVersion: v1
kind: Service
metadata:
  labels:
    app: toolbox-hadoop
  name: toolbox-hadoop
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 50070
      nodePort: 30060
  selector:
    app: toolbox-hadoop