apiVersion: v1
kind: Service
metadata:
  labels:
    app: toolbox-sonar
  name: toolbox-sonar
spec:
  type: NodePort
  ports:
    - name: toolbox-sonar
      port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 30070
  selector:
    app: toolbox-sonar