apiVersion: v1
kind: Service
metadata:
  labels:
    app: toolbox-spark
  name: toolbox-spark
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app: toolbox-spark