apiVersion: v1
kind: Service
metadata:
  labels:
    app: toolbox-jupyter
  name: toolbox-jupyter
spec:
  type: NodePort
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: 30090
  selector:
    app: toolbox-jupyter
  