apiVersion: apps/v1
kind: Deployment
metadata:
 name: toolbox-web
spec:
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     app: toolbox-web
 template:
   metadata:
     labels:
       app: toolbox-web
   spec:
     containers:
       - name: toolbox-web
         image: xuandif/toolbox-web:styled
         ports:
           - containerPort: 80